spring:
  datasource:
    # journal_mode=WAL 开启 WAL模式 支持并发读
    # busy_timeout=10000 超时时间 锁库自动重试10s
    # synchronous=NORMAL 同步模式 不要求直接刷到磁盘 性能和安全的平衡点
    url: "jdbc:sqlite:testDB.db?journal_mode=WAL&busy_timeout=10000&synchronous=NORMAL"
    driver-class-name: org.sqlite.JDBC
    hikari:
      maximum-pool-size: 8
      minimum-idle: 1

mybatis-plus:
  type-aliases-package: com.zw.sqliteTest.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: true